// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRiz9jWAx87PNAYY_RiVrm6FWLU6YgkY',
    appId: '1:122601417017:web:4027e6f5b260ed3516e0e8',
    messagingSenderId: '122601417017',
    projectId: 'chat-app-test-238fc',
    authDomain: 'chat-app-test-238fc.firebaseapp.com',
    storageBucket: 'chat-app-test-238fc.appspot.com',
    measurementId: 'G-E9S4FENT47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrzs4iwPH8nMjNenqTODSaNwBZ3x-cnQ',
    appId: '1:122601417017:android:52521c31a9d6adda16e0e8',
    messagingSenderId: '122601417017',
    projectId: 'chat-app-test-238fc',
    storageBucket: 'chat-app-test-238fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgk6UMepfZ9ZYx66YzUt_sAmPutGIZOU',
    appId: '1:122601417017:ios:3dbf4eebe149032b16e0e8',
    messagingSenderId: '122601417017',
    projectId: 'chat-app-test-238fc',
    storageBucket: 'chat-app-test-238fc.appspot.com',
    iosClientId: '122601417017-u63mdoedakf1ohpan0fp9ta4o9hngl9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
